### ISSUE TITLE
sorry this will not work under root 

### ISSUE THREAD

**Issue by rtulke** [pragbits/pydialog-interfaces#1]
Hey i cant start your script i got a import error?

```
root@mail:~# python -m site --user-site
/root/.local/lib/python2.7/site-packages

root@mail:~# mkdir -p /root/.local/lib/python2.7/site-packages

root@mail:~# git clone https://github.com/dggreenbaum/debinterface.git  /root/.local/lib/python2.7/site- packages
Cloning into '/root/.local/lib/python2.7/site-packages'...
remote: Counting objects: 191, done.
remote: Total 191 (delta 0), reused 0 (delta 0), pack-reused 191
Receiving objects: 100% (191/191), 47.81 KiB, done.
Resolving deltas: 100% (113/113), done.

root@mail:~# ls -la ~/.local/lib/python2.7/site-packages/
total 76
drwxr-xr-x 3 root root  4096 Jul 31 19:02 .
drwxr-xr-x 3 root root  4096 Jul 31 19:01 ..
-rw-r--r-- 1 root root 10186 Jul 31 19:02 adapter.py
-rw-r--r-- 1 root root  4531 Jul 31 19:02 dnsmasqRange.py
drwxr-xr-x 8 root root  4096 Jul 31 19:02 .git
-rw-r--r-- 1 root root    49 Jul 31 19:02 .gitignore
-rw-r--r-- 1 root root  5110 Jul 31 19:02 hostapd.py
-rw-r--r-- 1 root root     0 Jul 31 19:02 __init__.py
-rw-r--r-- 1 root root  3325 Jul 31 19:02 interfaces.py
-rw-r--r-- 1 root root  5241 Jul 31 19:02 interfacesReader.py
-rw-r--r-- 1 root root  5858 Jul 31 19:02 interfacesWriter.py
-rw-r--r-- 1 root root  1506 Jul 31 19:02 LICENSE
-rw-r--r-- 1 root root  1658 Jul 31 19:02 README.md
-rw-r--r-- 1 root root   946 Jul 31 19:02 toolutils.py

root@mail:~# pwd
/root

root@mail:~# wget https://raw.githubusercontent.com/pragbits/pydialog-interfaces/master/pydialog-interfaces.py

root@mail:~# chmod +x pydialog-interfaces.py

root@mail:~# ls -l
total 20
-rwxr-xr-x 1 root root 5815 Jul 31 18:54 pydialog-interfaces.py

 root@mail:~# ./pydialog-interfaces.py
 Traceback (most recent call last):
  File "./pydialog-interfaces.py", line 10, in <module>
    from debinterface.interfaces import interfaces
 ImportError: No module named debinterface.interfaces
```

**Comment by dszabo** [comment]
please have a `debinterface` directory under  your `/root/.local/lib/python2.7/site-packages` folder instead of putting the contents there directly. So the command to use would be:

`git clone https://github.com/dggreenbaum/debinterface.git  /root/.local/lib/python2.7/site-packages/debinterface`

... and don't use root for experimenting, always use a regular user account ;)

**Comment by rtulke** [comment]
hmm you a right with the root experimenting but this is one of my test hosts... :) but that will also not work for me :(

```
root@mail:~# git clone https://github.com/dggreenbaum/debinterface.git /root/.local/lib/python2.7/site-packages/debinterface
Cloning into '/root/.local/lib/python2.7/site-packages/debinterface'...
remote: Counting objects: 191, done.
remote: Total 191 (delta 0), reused 0 (delta 0), pack-reused 191
Receiving objects: 100% (191/191), 47.81 KiB, done.
Resolving deltas: 100% (113/113), done.
root@mail:/home/cray# cd /root/
root@mail:~# ls
bin  pydialog-interfaces.py
root@mail:~# python pydialog-interfaces.py
Traceback (most recent call last):
  File "pydialog-interfaces.py", line 10, in <module>
    from debinterface.interfaces import interfaces
ImportError: cannot import name interfaces
´´´
```

**Comment by rtulke** [comment]
Any other ideas?

**Comment by rtulke** [comment]
root@mail:~# uname -a
Linux mail 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1+deb7u1 x86_64 GNU/Linux

root@mail:~# python -V
Python 2.7.3

root@mail:~# dpkg -l |grep dialog
ii  dialog                             1.1-20120215-2                amd64        Displays user-friendly dialog boxes from shell scripts

**Comment by rtulke** [comment]
Ok strange i tested this with a normal user :) and that is working!

**Comment by rtulke** [comment]
closed

**Comment by pragbits** [comment]
Thanks for the reply. I just tried out quickly on a debian vm and it also worked for me using root, strange.

**Comment by pragbits** [comment]
One idea I have is that you may have $PYTHONPATH set up in your environment that ignores that search path there.

https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH

**Comment by pragbits** [comment]
You could also move this debinterface folder to the global site packages. Here is how you find out where is it in your env:

> > > import site; site.getsitepackages()
> > > ['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
